### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ghrom** [johnboiles/JBDaylightOverlay#1]
Cool stuff. Is there any chance to get this under BSD/apache style license instead of GNU, please? I'd love to add it to my little project but I can't use it if it's GNU.

**Comment by johnboiles** [comment]
That sounds reasonable, since GPL can be interpreted as incompatible with the App Store. Let me read a little about licenses. I'll close this issue when I change it.

**Comment by johnboiles** [comment]
Sorry for the delay here, I changed the license to New BSD. I'd love to hear about what you build!

**Comment by ghrom** [comment]
Hi John,

Many thanks for that. I've just added you work to my iMtG app, the version with your code in should hit the store within a month. I've added you to credits: http://imtgapp.com/legal.html the app itself is here http://itunes.apple.com/us/app/imtg/id412798013?mt=8

Cheers,
Piotr

**Comment by johnboiles** [comment]
Neat! I look forward to seeing it!

(Sent from my iPhone)
